In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


**Introduction to tensors**

Creating tensors

In [9]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim

0

In [15]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [16]:
vector.ndim

1

In [17]:
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim

2

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [27]:
### Random tensors
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.8828, 0.1345, 0.1327, 0.9911],
         [0.8597, 0.6038, 0.7347, 0.6662],
         [0.7278, 0.5531, 0.0217, 0.4849]]])

In [28]:
random_tensor.ndim

3

In [29]:
random_tensor.shape

torch.Size([1, 3, 4])

In [30]:
# Image sized tensors
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)