In [34]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


**Introduction to tensors**

Creating tensors

In [35]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [36]:
scalar.ndim

0

In [37]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [38]:
vector.ndim

1

In [39]:
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [40]:
MATRIX.ndim

2

In [41]:
MATRIX.shape

torch.Size([2, 2])

In [42]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [43]:
TENSOR.ndim

3

In [44]:
TENSOR.shape

torch.Size([1, 3, 3])

In [45]:
### Random tensors
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.8385, 0.3709, 0.2643, 0.4672],
         [0.2361, 0.9327, 0.3509, 0.4229],
         [0.8625, 0.7513, 0.7316, 0.1899]]])

In [46]:
random_tensor.ndim

3

In [47]:
random_tensor.shape

torch.Size([1, 3, 4])

In [48]:
# Image sized tensors
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Tensor Datatypes

In [49]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype the tensor is
                               device=None, #cpu or GPU(cuda), what device the tensor is on
                               requires_grad=False) #whether to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [50]:
float_32_tensor.dtype

torch.float32

In [51]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [52]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [53]:
float_16_tensor* float_32_tensor

tensor([ 9., 36., 81.])

In [54]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [55]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

Getting Information from tensors

datatype - tensor.dytpe
shape - tensor.shape
device - tensor.device

In [56]:
#Create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8292, 0.0178, 0.6555, 0.6665],
        [0.6401, 0.3606, 0.5568, 0.6968],
        [0.2674, 0.4816, 0.7993, 0.8013]])

In [57]:
# Finding details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8292, 0.0178, 0.6555, 0.6665],
        [0.6401, 0.3606, 0.5568, 0.6968],
        [0.2674, 0.4816, 0.7993, 0.8013]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors - Tensor operations

*Addition
*Subtraction
*Multiplication(element-wise)
*Division
*Matrix multiplication

In [58]:
#Create tensor and add
tensor = torch.tensor([1,2,3])
tensor + 10



tensor([11, 12, 13])

In [59]:
#multiply by 10
tensor * 10

tensor([10, 20, 30])

In [60]:
#Subtract
tensor - 10

tensor([-9, -8, -7])

In [61]:
#Pytorch inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [62]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [63]:
# Finding tensor aggregation
#Create a tensor
x = torch.arange(0,100,10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
#Finding the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [65]:
#Finding the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [66]:
#Finding mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [67]:
#Finding sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [68]:
# Finding positional min and max
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [69]:
x.argmin()

tensor(0)

In [70]:
x.argmax()

tensor(9)