In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


**Introduction to tensors**

Creating tensors

In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
### Random tensors
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.2234, 0.4840, 0.6587, 0.6882],
         [0.7755, 0.1944, 0.3648, 0.5626],
         [0.5559, 0.9210, 0.9820, 0.9573]]])

In [17]:
random_tensor.ndim

3

In [18]:
random_tensor.shape

torch.Size([1, 3, 4])

In [19]:
# Image sized tensors
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Tensor Datatypes

In [20]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype the tensor is
                               device=None, #cpu or GPU(cuda), what device the tensor is on
                               requires_grad=False) #whether to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [21]:
float_32_tensor.dtype

torch.float32

In [22]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [24]:
float_16_tensor* float_32_tensor

tensor([ 9., 36., 81.])

In [25]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [26]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

Getting Information from tensors

datatype - tensor.dytpe
shape - tensor.shape
device - tensor.device

In [27]:
#Create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1317, 0.8538, 0.9607, 0.5322],
        [0.8352, 0.4405, 0.2417, 0.9273],
        [0.9898, 0.9456, 0.2481, 0.7865]])

In [28]:
# Finding details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1317, 0.8538, 0.9607, 0.5322],
        [0.8352, 0.4405, 0.2417, 0.9273],
        [0.9898, 0.9456, 0.2481, 0.7865]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors - Tensor operations

*Addition
*Subtraction
*Multiplication(element-wise)
*Division
*Matrix multiplication

In [29]:
#Create tensor and add
tensor = torch.tensor([1,2,3])
tensor + 10



tensor([11, 12, 13])

In [30]:
#multiply by 10
tensor * 10

tensor([10, 20, 30])

In [31]:
#Subtract
tensor - 10

tensor([-9, -8, -7])

In [32]:
#Pytorch inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [33]:
torch.add(tensor,10)

tensor([11, 12, 13])